#!/usr/bin/env node

/**
 * Interactive Environment Variables Setup Script
 * Helps you create .env.local with all required API keys
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function setup() {
  console.log('🔐 Environment Variables Setup\n');
  console.log('This script will help you create your .env.local file.\n');
  console.log('⚠️  Make sure you have your API keys ready!\n');

  const envVars = {};

  // Required variables
  console.log('=== REQUIRED VARIABLES ===\n');

  // Supabase
  console.log('📦 Supabase (Database)');
  console.log('   Get from: https://supabase.com/dashboard/project/_/settings/api\n');
  envVars.NEXT_PUBLIC_SUPABASE_URL = await question('NEXT_PUBLIC_SUPABASE_URL: ');
  envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY = await question('NEXT_PUBLIC_SUPABASE_ANON_KEY: ');
  envVars.SUPABASE_SERVICE_ROLE_KEY = await question('SUPABASE_SERVICE_ROLE_KEY: ');
  console.log('');

  // OpenAI
  console.log('🤖 OpenAI (AI Features)');
  console.log('   Get from: https://platform.openai.com/api-keys\n');
  envVars.OPENAI_API_KEY = await question('OPENAI_API_KEY: ');
  console.log('');

  // Site URL
  console.log('🌐 Site URL (Optional - press Enter for default)');
  const siteUrl = await question('NEXT_PUBLIC_SITE_URL: ');
  if (siteUrl.trim()) {
    envVars.NEXT_PUBLIC_SITE_URL = siteUrl.trim();
  }
  console.log('');

  // Optional variables
  console.log('\n=== OPTIONAL VARIABLES ===');
  console.log('Press Enter to skip any optional variables\n');

  // GoHighLevel
  const ghlKey = await question('GOHIGHLEVEL_API_KEY (optional): ');
  if (ghlKey.trim()) {
    envVars.GOHIGHLEVEL_API_KEY = ghlKey.trim();
    const ghlLocation = await question('GOHIGHLEVEL_LOCATION_ID (optional): ');
    if (ghlLocation.trim()) {
      envVars.GOHIGHLEVEL_LOCATION_ID = ghlLocation.trim();
    }
  }

  // Vapi
  const vapiKey = await question('VAPI_API_KEY (optional): ');
  if (vapiKey.trim()) {
    envVars.VAPI_API_KEY = vapiKey.trim();
  }

  // Inngest
  const inngestSigning = await question('INNGEST_SIGNING_KEY (optional): ');
  if (inngestSigning.trim()) {
    envVars.INNGEST_SIGNING_KEY = inngestSigning.trim();
    const inngestEvent = await question('INNGEST_EVENT_KEY (optional): ');
    if (inngestEvent.trim()) {
      envVars.INNGEST_EVENT_KEY = inngestEvent.trim();
    }
  }

  // Redis
  const redisUrl = await question('UPSTASH_REDIS_URL (optional): ');
  if (redisUrl.trim()) {
    envVars.UPSTASH_REDIS_URL = redisUrl.trim();
  }

  // Generate .env.local content
  let envContent = '# Environment Variables for Ace Electric Parts System\n';
  envContent += '# Generated by setup-env.js\n\n';

  envContent += '# ============================================\n';
  envContent += '# REQUIRED\n';
  envContent += '# ============================================\n\n';

  envContent += `NEXT_PUBLIC_SUPABASE_URL=${envVars.NEXT_PUBLIC_SUPABASE_URL}\n`;
  envContent += `NEXT_PUBLIC_SUPABASE_ANON_KEY=${envVars.NEXT_PUBLIC_SUPABASE_ANON_KEY}\n`;
  envContent += `SUPABASE_SERVICE_ROLE_KEY=${envVars.SUPABASE_SERVICE_ROLE_KEY}\n\n`;
  envContent += `OPENAI_API_KEY=${envVars.OPENAI_API_KEY}\n\n`;

  if (envVars.NEXT_PUBLIC_SITE_URL) {
    envContent += `NEXT_PUBLIC_SITE_URL=${envVars.NEXT_PUBLIC_SITE_URL}\n\n`;
  }

  if (Object.keys(envVars).some(k => k.startsWith('GOHIGHLEVEL') || k.startsWith('VAPI') || k.startsWith('INNGEST') || k.startsWith('UPSTASH'))) {
    envContent += '# ============================================\n';
    envContent += '# OPTIONAL\n';
    envContent += '# ============================================\n\n';

    if (envVars.GOHIGHLEVEL_API_KEY) {
      envContent += `GOHIGHLEVEL_API_KEY=${envVars.GOHIGHLEVEL_API_KEY}\n`;
      if (envVars.GOHIGHLEVEL_LOCATION_ID) {
        envContent += `GOHIGHLEVEL_LOCATION_ID=${envVars.GOHIGHLEVEL_LOCATION_ID}\n`;
      }
      envContent += '\n';
    }

    if (envVars.VAPI_API_KEY) {
      envContent += `VAPI_API_KEY=${envVars.VAPI_API_KEY}\n\n`;
    }

    if (envVars.INNGEST_SIGNING_KEY) {
      envContent += `INNGEST_SIGNING_KEY=${envVars.INNGEST_SIGNING_KEY}\n`;
      if (envVars.INNGEST_EVENT_KEY) {
        envContent += `INNGEST_EVENT_KEY=${envVars.INNGEST_EVENT_KEY}\n`;
      }
      envContent += '\n';
    }

    if (envVars.UPSTASH_REDIS_URL) {
      envContent += `UPSTASH_REDIS_URL=${envVars.UPSTASH_REDIS_URL}\n\n`;
    }
  }

  envContent += 'NODE_ENV=development\n';

  // Write to file
  const envPath = path.join(process.cwd(), '.env.local');
  
  if (fs.existsSync(envPath)) {
    const overwrite = await question(`\n⚠️  .env.local already exists. Overwrite? (y/N): `);
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Cancelled.');
      rl.close();
      return;
    }
  }

  fs.writeFileSync(envPath, envContent);
  console.log(`\n✅ Created .env.local successfully!`);
  console.log(`\n📋 Next steps:`);
  console.log(`   1. Review your .env.local file`);
  console.log(`   2. Run: npm run verify:setup`);
  console.log(`   3. Add to Vercel: Dashboard → Settings → Environment Variables`);
  console.log(`\n🔒 Remember: Never commit .env.local to Git!`);

  rl.close();
}

setup().catch((error) => {
  console.error('Error:', error);
  rl.close();
  process.exit(1);
});

